author: liujiuwu@gmail.com
description: >
        Hmm. this is a test.
        hahaha

filesets:
    excludes:
        - \.git
    depth: 3
settings:
        targetdir: ""
        build: |
            test -d Godeps && go(){ godep go "$@";} ; go install -v
        outfiles:
            - packer